### ISSUE TITLE
2024-09-16 -- Eva Tasks

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#138]
# Tasks for Today

- [ ] Schedule regular advising meeting w/ Nic
- [ ] Schedule regular research meeting w/ Nic
- [x] List remaining computational work for QSS paper on Researcher-GitHub User EM
  - **Done:** https://github.com/evamaxfield/rs-graph/issues/29
- [x] Start drafting QSS paper on Research-GitHub User EM
  - Use template from Nic: [Project-Paper-Outline-Template](https://docs.google.com/document/d/1KjNgiLUXO_jVuwTkTHp6wyBJr9KXHY2LJOyXowHkMCc/edit?usp=sharing)
  - **Started:** Bullet point outline of Introduction (nearly fully filled out), Data and Methods (starting to fill out), and Results (just top level) [link](https://docs.google.com/document/d/1kb9MCfYBZmSxZWiof2rFdEChTSIGiSoW5gg4KhBVWFI/edit?usp=sharing)

## Ongoing

- [ ] Check in on EAGER GROBID processing / likely need to restart server and come up with better long-term processing solution -- maybe [coiled](https://www.coiled.io/)
- [ ] Eva free-time: migrate EM model training and application code from [rs-graph](https://github.com/evamaxfield/rs-graph) to local repo: `scisoft-models`
  - In relation to the QSS paper my goal here was to separate the model _usage_ utilities from the larger pipeline so that others (including ourselves) can use the model without installing the whole `rs-graph` library as it is _very_ heavy.
  - Related issue: https://github.com/evamaxfield/rs-graph/issues/27

## Conferences

- [x] Handle OFE Symposium Travel
- [ ] Message Sabina & Wolfgang to schedule meetings while at Ann Arbor

**Comment by evamaxfield** [comment]
# EoD Checkin

## Tasks for Today

- Proposed meeting times for advising + RA meetings w/ Nic, waiting on response
- Listed out what I believe is the remaining computational work on QSS Software Credit and Authorship paper. Available at: https://github.com/evamaxfield/rs-graph/issues/29
- Drafted out QSS Software Credit and Authorship paper: Introduction (nearly fully filled out), Data and Methods (starting to fill out), Results (top level bullets). Available at: [google doc](https://github.com/evamaxfield/rs-graph/issues/29)

## Closing out Today

- Going to end the day with just a bit of work on the "remaining computational work for QSS Software Credit" -- focusing on getting the processing pipeline back up and running and starting processing JOSS + PwC
