### ISSUE TITLE
2024-09-17 -- Eva Tasks

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#139]
Previous Day's Tasks: #138 

# Tasks for Today

- [x] Continue draft of QSS Software Credit and Authorship
  - Focus on finishing methods and lit review
- [x] Continue working on getting the pipeline back up and running
  - Environment correctly managed
  - Regenerate all required keys
  - Check Prod DB
  - Process JOSS

## Ongoing

- [ ] Check in on EAGER GROBID processing server
- [ ] Eva free-time: migrate EM model training and application code to new repo

## Conferences

- [x] Message Sabina and Wolfgang to schedule meetings while at Ann Arbor

**Comment by evamaxfield** [comment]
# EoD Check-in

## Tasks for Today

- Continued to work on QSS Software Credit and Authorship draft
  - The data and methods section is now fully bullet pointed out
  - I think this is a good stopping point for now until I meet with Nic to get feedback / guidance on where to focus my writing efforts next (or, if there are general structural problems so far).

- Continued to work on getting the pipeline back up and running
  - Happy to report that I got the rs-graph pipeline basically fully up and running.
  - Realized that I need to put my effort towards splitting out the EM model training and application code because the current pipeline implementation uses the old prototype author-dev matching model and not the best one we trained.
  - I don't think this should take too long to do, most of that code has already been split out but it is something to get done and out of the way before I can really get the pipeline fully working.
  - This also done mean, imo, that we should reprocess the existing data. I am really not too concerned about this because all of PLOS and JOSS can be processed in a single day so getting the upgraded model in is a generally good move IMO.
- Messaged Sabina and Wolfgang about meeting while I am in Ann Arbor, hopefully I can schedule some meetings with them / their labs!

## Closing out Today

- Going to write a quick message to Nic with my notes for advising meeting tomorrow
