### ISSUE TITLE
2024-09-18 -- Eva Tasks

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#140]
Previous Day's Tasks: #139

# Tasks for Today

- [ ] Continue draft of QSS Software Credit and Authorship
  - Focus on responding to feedback from Nic + likely Lit Review section
- [x] Work on moving the model training and application code for author-developer account EM to its own library
- [x] Write out a refresher of what we have done so far for EAGER work and what we might consider working on next to get a publication out of that work
- [x] Check in on GROBID server and get that back up and running

## Conferences / Travel

- [ ] Submit OFE Symposium travel details for reimbursement
- [ ] Respond to Sabina + Wolfgang / plan out time in Michigan
- [ ] Eva free-time: bullet point out the results of GitHub software releases work in Overleaf for OFE Symposium

## Admin

- [x] Schedule RA meeting w/ Nic for the days I am remote, otherwise, plan for normal schedule

**Comment by evamaxfield** [comment]
Feedback from @nniiicc on current outline:

- Structure into:
  - Introduction (which includes some of the background)
  - Data
    - PLOS, JOSS, PwC as sources
    - OpenAlex for Bibliometric Info
    - GitHub for Code Repository Info
    - Make a table of what data we have and were we get that data
  - Model
    - Start with our task
    - How to get there (need to annotate)
    - Train the model
    - Results on our task
  - Analysis (which includes data description)
- Also think about the research design. Consider reframing into: there is current work in understanding the contributions of scientific software developers but most is done qualitatively, to enable quantitative approaches we develop a new predictive model to match authors and developer accounts together, we demonstrate the utility of such a model by applying it and working on preliminary analysis of labor distribution on research teams from three distinct article types.

The paper should be framed as "the model is a major contribution and the analysis is preliminary" to set us up for future work which dives deeper into career trajectories and more in-depth study of developer contribution and impact.

In that vein: rephrase the research questions / contributions of the paper.
