### ISSUE TITLE
2024-09-20 -- Eva Tasks

### ISSUE THREAD

**Issue by evamaxfield** [PugetSoundClinic-PIT/ProjectTracking#143]
Previous Tasklist: #140 

# Tasks for Today

- [x] Work on #142 -- starting with getting a repo cloning script up and running and getting basic metrics out of the commit log
- [ ] Bullet point out research questions + argument + data + analysis for EAGER work
- [x] Prep for plane ride by setting up local writing environment (for all three papers)

## Conferences

- [ ] Submit OFE Symposium travel details for reimbursement (need BECU help)
- [x] Respond to Sabina + Wolfgang / plan out time in Michigan

**Comment by evamaxfield** [comment]
# EoD Check-in

- Got cloning of the repos working and I _think_ I figured out how I want to store the repo metric data (i.e. all of the commit deltas + daily summary statistics).
  - There are sadly some repos which don't clone and I am not sure why. Worth investigating imo because we only have ~1100 repo + grant pairs.

- Downloaded the QSS paper draft as markdown to work on during plane rides + starting a new local markdown document for EAGER bullet point outline, finally, downloaded the existing tex file that has the in-progress OFE symposium paper draft.
